### ISSUE TITLE
Change Artwork on schedule

### ISSUE THREAD

**Issue by marshalmiller** [maxvfischer/DIY-ai-art#37]
Would it be possible to have the art change every hour, instead of by the push of a button?

**Comment by maxvfischer** [comment]
Hi @marshalmiller ! 

Yeah, absolutely. In fact, it's much more easy to do that, as you don't have to listen to any GPIO pins. 

If I were you I would create a fork of this repo, rename the class `ArtButton` to something like `ArtCronJob`. Then update the `ArtCronJob` class by e.g.:
* Remove all GPIO arguments.
* Add an argument defining the number of seconds before the artwork should be changed. Save that argument to a new class variable called `self.seconds_before_artwork_change`
* Add a class variable called `self.time_last_image_change = datetime.datetime.now()`
* Update the function `def start()` to something similar to this:
```python
def start(self) -> None:
    """Starts infinate loop listening to button click. When clicked, it changes the active artwork."""
    while True:
        if (datetime.datetime.now() - self.time_last_image_change).seconds > self.seconds_before_artwork_change:
            self._change_active_artwork()
```
* Remove the function `def _is_false_negative_click()`

I have not tried the code above, it's just a hint of how you could change it.

**Comment by maxvfischer** [comment]
I'm closing this issue. Just write here again if you have any other questions and I'll re-open it.

**Comment by maxvfischer** [comment]
No problem, just fun to see that the repo is coming to use :) Feel free to shoot me a message if you struggle with something or have any questions.

**Comment by marshalmiller** [comment]
Hey @maxvfischer I am still working on this project right now. It's located here. https://github.com/marshalmiller/AIArt.
I seem to be having a few issues right now. First I am getting these errors and I'm a little confused as to what I am doing wrong.
`./kiosk/artcronjob.py:6:11: E999 SyntaxError: invalid syntax
class self.seconds_before_artwork_change()
          ^
./kiosk/art_event_handler.py:51:18: F821 undefined name 'tf'
        config = tf.ConfigProto(allow_soft_placement=True)
                 ^
./kiosk/art_event_handler.py:52:14: F821 undefined name 'tf'
        with tf.Session(config=config) as sess:
             ^
./kiosk/art_event_handler.py:53:20: F821 undefined name 'StyleGAN'
             gan = StyleGAN(
                   ^
1     E999 SyntaxError: invalid syntax
3     F821 undefined name 'tf'`

Lastly, I was wondering if you could expand on the idea of adding my own generative code. Where would I get that or resources to make my own if needed? I'm really into this project and am just hoping to get it up and going at some point. Thank you for all of your help so far and any that you might provide in the future. Feel free to address these issues on my project if you want to keep this space clean.

**Comment by maxvfischer** [comment]
Hey @marshalmiller 

Awesome that you're still working on it! Have you decided on what art to display?

It's a bit difficult to track the errors because of how they got printed in the comment, but I'll give it a try to point you in the right direction:

* `undefined name 'tf'`: You haven't imported Tensorflow (`import Tensorflow as tf`) in `art_event_handler.py`, which most likely throws the errors.
* `undefined name 'StyleGAN'`: It seems like you've just uncommented my example code, which will not work as long as you don't implement your own generative code that uses Tensorflow and name it in the same way. I intentionally removed all my generative code to enable people to implement their own.
* `./kiosk/artcronjob.py:6:11: E999 SyntaxError: invalid syntax class self.seconds_before_artwork_change()`: I'm not sure that that's an allowed way to define a class. One way of solving it could be to moving the `self.seconds_before_artwork_change` as an instance variable in your class `ArtCronJob` and set it to `3600`. Then you should be able to access it?
* The same goes for `class self.time_last_image_change = datetime.datetime.now()` in `art_event_handler.py`, I'm not sure that that's an allowed way of defining a class.
* Also, you're not importing `datetime` in `art_event_handler.py`, which most likely will throw an error as well.

Btw, is there a reason why you didn't fork my work and continue on it in that way? Now you've just copied the code and pushed it as your own repo. I will of course allow you to do it, but it would be nice with an attribution :)

**Comment by marshalmiller** [comment]
I have not picked one yet, but I was planning on using a dataset of images from an art gan or Wikipedia has some. But I wasn't sure how that worked with the GAN code stuff.

Thank you for pointing me in the right direction. I will certainly give these a try.

Regarding the fork. I actually did fork it initially but I kept accidentally creating pull requests and I didn't want to interrupt your project. I still have the fork. But I created one to work in until I had it all figured out. I don't have the right account for private repositories either. Or else I would hide it. My ReadME is a mess right now, but the intention was fully to give you the first paragraph and link back to your original project. I'm just trying to figure out how to get this working.

**Comment by maxvfischer** [comment]
Ok! Yeah, you first need to train a GAN network using the images you've chosen. Then you replace my sample code with your own code that generates images using your own GAN. 

If you've not that familiar with training GANs, I can recommend you to check out Google Colab Pro, it costs $9.99/month, but will enable you to get access to otherwise quite expensive GPUs. But the downside is that it has a runtime limit of 24h, so you need to save your GAN checkpoints somewhere (e.g. on Google Drive) and restart the notebook and load the checkpoints again to continue the training.

Just to give you a hint of how long it took to train my GAN, I think it took me ~14 days (without interruption) to train a StyleGAN to 1024x1024 resolution on a Tesla P100, when using ~5000 images. Using fewer images and reducing the output resolution of the images will lower the training time.

Hehe alright! No probs, do it if you want :)

**Comment by marshalmiller** [comment]
OK. I have trained my models now. I'm a little confused about the code part though. I have my generator and my discriminator. I don't quite understand how I plug that into the code though?

**Comment by maxvfischer** [comment]
You will only need the generator, as that's the network that will generate new images. It's a bit difficult for me to know exactly what you need to know, but I would guess it's something in the lines of this:

1. Copy over the checkpoint (trained weights) of the generator to the repository.
2. Write a class that can be triggered to generate images that are then saved in the pre-defined `image directory`.
3. Update the function `def generate_images` in `art_event_handler.py` to load the checkpoints and generate the images.
